Repository Unionz-CallinU/INU-phonebook-server, pull requests merged in 2023-07, with the labels that each got.

#3 [Style] PR 템플릿 재구성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🧹 Clean Up

#8 [Develop] domain, exception 설계
  inu-phonebook/src/main/java/com/example/inuphonebook/common/domain/Message.java
  inu-phonebook/src/main/java/com/example/inuphonebook/common/exception/BadRequestException.java
  inu-phonebook/src/main/java/com/example/inuphonebook/common/exception/CommonException.java
  inu-phonebook/src/main/java/com/example/inuphonebook/common/exception/NotFoundException.java
  inu-phonebook/src/main/java/com/example/inuphonebook/domain/Department.java
  inu-phonebook/src/main/java/com/example/inuphonebook/domain/Employee.java
  inu-phonebook/src/main/java/com/example/inuphonebook/domain/Office.java
  inu-phonebook/src/main/java/com/example/inuphonebook/domain/Professor.java
  inu-phonebook/src/main/java/com/example/inuphonebook/domain/Staff.java
  inu-phonebook/src/main/java/com/example/inuphonebook/domain/UniHeadquarters.java
  inu-phonebook/src/main/java/com/example/inuphonebook/repository/CollegeRepository.java
  inu-phonebook/src/main/java/com/example/inuphonebook/repository/EmployeeRepository.java
  inu-phonebook/src/main/java/com/example/inuphonebook/repository/ProfessorRepository.java
Labels: ♻️ Refactoring, ⚡️ New Feature

#9 [Develop] domain 수정
  inu-phonebook/src/main/java/com/example/inuphonebook/domain/College.java
  inu-phonebook/src/main/java/com/example/inuphonebook/domain/Department.java
  inu-phonebook/src/main/java/com/example/inuphonebook/domain/Employee.java
  inu-phonebook/src/main/java/com/example/inuphonebook/repository/EmployeeRepository.java
Labels: ⚡️ New Feature
